fix: remove deprecated `incompatible_use_toolchain_transition` (#114)
We hit this issue while attempting to upgrade to Bazel 9.x: 

```
ERROR: Traceback (most recent call last):
        File "/Users/wburgin/Library/Caches/bazel/_bazel_wburgin/591e37aa54c94fef8ee5e1f35bda4175/external/aspect_rules_cypress++cypress+cypress_toolchains/defs.bzl", line 15, column 20, in <toplevel>
                resolved_toolchain = rule(
Error in rule: rule() got unexpected keyword argument 'incompatible_use_toolchain_transition'
```

I'm not familiar with this flag, but based on
[this](https://github.com/bazelbuild/bazel/commit/f53608ac3dbfd02cecb4bb78a138badb0d84e311)
it seems to be deprecated and was removed entirely in Bazel 9.

---

### Changes are visible to end-users: no

### Test plan

Manually tested with a patch in our internal monorepo

Co-authored-by: Jason Bedard <jason+github@jbedard.ca>